-- ============================================
-- LIMITE LIMITE - Seed des cartes de départ
-- 190 questions (cards_questions) + 100 réponses (cards_answers)
-- Toutes "hidden = false" (deck visible par défaut)
-- ============================================

insert into cards_questions (text, blanks) values
('Pour me féliciter d''avoir eu le bac, mes parents m''ont offert _____', 1),
('_____, ça résume bien mon adolescence', 1),
('Quand je suis bourré, j''ai tendance à confondre _____ et _____', 2),
('_____ me donne vraiment la gerbe', 1),
('Le pire cadeau que j''ai reçu de Mamie : _____', 1),
('Mon excuse préférée pour ne pas aller au travail : _____', 1),
('Dans 10 ans, je serai connu pour _____', 1),
('La pire chose à dire le jour de son mariage : _____', 1),
('Ce que je cache dans l''historique de mon téléphone : _____', 1),
('Le secret de famille que personne ne devait connaître : _____', 1),
('Si j''étais président, ma première loi serait sur _____', 1),
('La pire excuse pour arriver en retard : _____', 1),
('Mon plus grand talent caché : _____', 1),
('Ce qu''on entend à travers les murs de la chambre des parents : _____', 1),
('La chose la plus gênante trouvée dans le sac de mon coloc : _____', 1),
('_____, ça c''est typiquement français', 1),
('Le pire souvenir de colonie de vacances : _____', 1),
('Ce que je ferais si je gagnais au loto : _____', 1),
('La pire chose à crier pendant un enterrement : _____', 1),
('Mon coach sportif m''a dit d''arrêter _____', 1),
('La nouvelle tendance TikTok la plus ridicule : _____', 1),
('Ce qu''on ne devrait jamais googler au travail : _____', 1),
('Mon thérapeute me dit que je devrais arrêter de penser à _____', 1),
('Le pire prénom à donner à un enfant : _____', 1),
('Ce qui pourrait être écrit sur ma pierre tombale : _____', 1),
('La chose la plus chère que j''ai achetée alcoolisé : _____', 1),
('Si les animaux pouvaient parler, ils diraient _____ aux humains', 1),
('Mon ex m''a quitté à cause de _____', 1),
('Ce que je ferais pour 1 million d''euros : _____', 1),
('La pire réponse à donner à un entretien d''embauche : _____', 1),
('_____ est interdit dans mon pays natal', 1),
('Le pire moment pour recevoir un appel de sa mère : _____', 1),
('Ce que je n''ai jamais avoué à mon meilleur ami : _____', 1),
('La pire chose à entendre de la bouche de son médecin : _____', 1),
('Mon plan pour survivre à la fin du monde : _____', 1),
('Ce que je ferais en premier si j''étais invisible : _____', 1),
('La pire blague à raconter pendant un dîner de famille : _____', 1),
('Ce que je regrette le plus de mes années lycée : _____', 1),
('_____, le secret des couples qui durent', 1),
('La pire chose à faire pendant un Zoom professionnel : _____', 1),
('Mon profil de rencontre dirait : "Recherche personne pour _____"', 1),
('Ce que je n''ai jamais dit à mes parents : _____', 1),
('La pire chanson à mettre lors d''un mariage : _____', 1),
('Si on me payait pour ne plus jamais faire _____, j''accepterais', 1),
('La pire question qu''on m''ait posée à un entretien : _____', 1),
('Ce que je dirais à mon moi de 15 ans : _____', 1),
('La chose la plus bizarre que j''ai mangée par défi : _____', 1),
('Le pire conseil que j''ai reçu de mes parents : _____', 1),
('_____ est devenu un sport olympique cette année', 1),
('Ce qu''on devrait apprendre à l''école et qu''on n''apprend pas : _____', 1),
('La pire chose à dire pendant une garde à vue : _____', 1),
('Mon plus grand échec personnel : _____', 1),
('La pire chose qu''on m''ait dite après une rupture : _____', 1),
('Si j''avais un super pouvoir, ce serait _____', 1),
('Ce que je ferais si mon patron me convoquait soudainement : _____', 1),
('La pire chose à offrir à sa belle-mère : _____', 1),
('Mon application préférée est en fait _____', 1),
('La pire chose à dire à un examen oral : _____', 1),
('Ce que je n''ai jamais avoué à mon psy : _____', 1),
('_____ devrait être enseigné dès la maternelle', 1),
('La pire chose trouvée dans les toilettes d''un festival : _____', 1),
('Mon plus grand fantasme inavouable : _____', 1),
('La pire raison de se faire virer : _____', 1),
('Ce que je ferais si je croisais mon ex avec son/sa nouveau/nouvelle : _____', 1),
('La chose la plus honteuse cachée sous mon lit : _____', 1),
('Si Dieu existait, sa première question serait : "Pourquoi as-tu fait _____ ?"', 1),
('La pire excuse pour un retard de règles : _____', 1),
('Ce que je dirais si on me proposait de revivre ma vie : _____', 1),
('La pire chose à publier sur les réseaux après une soirée : _____', 1),
('Mon animal de compagnie pense probablement _____ de moi', 1),
('La pire chose à découvrir sur le téléphone de son/sa partenaire : _____', 1),
('Ce qui devrait être interdit dans les transports en commun : _____', 1),
('_____, voilà ce qui définit ma génération', 1),
('La pire blague de Tonton à Noël : _____', 1),
('Si je devais choisir un dernier repas avant de mourir : _____', 1),
('La pire chose à dire pendant un rendez-vous Tinder : _____', 1),
('Ce que je referais si j''avais 20 ans de moins : _____', 1),
('La pire chose vue en garde alternée chez papa : _____', 1),
('Mon plus grand mensonge à un employeur : _____', 1),
('_____ devrait être banni d''Internet', 1),
('La pire chose à crier pendant l''accouchement : _____', 1),
('Ce que je ferais si je devenais invisible une journée : _____', 1),
('La pire raison pour laquelle un couple s''est séparé : _____', 1),
('Mon plus grand regret de soirée arrosée : _____', 1),
('Ce que je porterais si j''étais SDF : _____', 1),
('La pire phrase à dire le premier jour au nouveau travail : _____', 1),
('Si j''étais un super-vilain, mon arme serait _____', 1),
('La pire chose découverte dans le frigo d''un coloc : _____', 1),
('Ce qui résume parfaitement un dimanche soir : _____', 1),
('La pire chose à faire pendant les vœux du Nouvel An : _____', 1),
('Mon plus grand traumatisme d''enfance : _____', 1),
('_____, c''est exactement le genre de truc qu''on regrette', 1),
('La pire raison d''appeler les pompiers : _____', 1),
('Ce que je dirais si je devais convaincre un alien de rester sur Terre : _____', 1),
('La pire chose entendue dans un vestiaire : _____', 1),
('Si les murs de mon appart pouvaient parler, ils raconteraient _____', 1),
('La pire chose à publier le jour de son anniversaire : _____', 1),
('Ce que mes voisins entendent à travers le mur : _____', 1),
('La pire chose à dire devant les beaux-parents : _____', 1),
('Mon plus grand fail en soirée d''entreprise : _____', 1),
('_____ devrait remplacer les cours de sport', 1),
('La pire chose vue sur le profil LinkedIn d''un ami : _____', 1),
('Ce que je ferais en cas d''alerte zombie : _____', 1),
('La pire blague que j''ai faite à un enterrement : _____', 1),
('Mon plus grand secret bien gardé : _____', 1),
('Si je devais inventer une nouvelle religion, son commandement serait : "Tu ne feras jamais _____"', 1),
('La pire chose à offrir comme cadeau de mariage : _____', 1),
('Ce qu''on trouve souvent dans les WC d''un bar : _____', 1),
('La pire phrase pour briser la glace lors d''un rendez-vous : _____', 1),
('Mon plus grand échec en cuisine : _____', 1),
('_____, ça devrait être le slogan de mon pays', 1),
('La pire chose à dire pendant une thérapie de couple : _____', 1),
('Ce que je ferais si je devenais célèbre du jour au lendemain : _____', 1),
('La pire chose découverte en fouillant les affaires d''un ex : _____', 1),
('Mon plus grand kiff coupable : _____', 1),
('La pire chose à dire en sortant de l''église après un mariage : _____', 1),
('Ce qui devrait figurer sur mon CV mais que je n''ose pas mettre : _____', 1),
('La pire excuse pour avoir loupé un cours important : _____', 1),
('Si j''étais réincarné, j''aimerais revenir en tant que _____', 1),
('La pire chose entendue à travers les murs d''un Airbnb : _____', 1),
('Mon plus grand fail en rendez-vous galant : _____', 1),
('_____ est mon péché mignon honteux', 1),
('La pire phrase entendue chez le coiffeur : _____', 1),
('Ce que je dirais sur mon lit de mort : _____', 1),
('La pire chose à faire pendant un entretien d''embauche en visio : _____', 1),
('Mon plus grand mensonge sur les réseaux sociaux : _____', 1),
('La pire chose à crier pendant un combat de boxe : _____', 1),
('Ce qui se cache vraiment derrière les sourires sur les photos de famille : _____', 1),
('La pire chose dite par un témoin lors d''un mariage : _____', 1),
('Mon plus grand fail vestimentaire : _____', 1),
('_____, c''est franchement n''importe quoi de nos jours', 1),
('La pire chose à découvrir en faisant le ménage de printemps : _____', 1),
('Ce que je ferais si je trouvais 1000€ par terre : _____', 1),
('La pire chose à dire le lendemain d''une soirée trop arrosée : _____', 1),
('Mon plus grand fantasme jamais avoué : _____', 1),
('La pire chose à offrir pour la Saint-Valentin : _____', 1),
('Ce qui devrait être interdit en salle de sport : _____', 1),
('La pire phrase entendue chez le psy : _____', 1),
('Mon plus grand traumatisme de colonie : _____', 1),
('_____, c''est carrément le pire truc qui existe', 1),
('La pire chose découverte dans l''historique Netflix de quelqu''un : _____', 1),
('Ce que je ferais si j''étais maire de ma ville : _____', 1),
('La pire chose à dire à son patron en démissionnant : _____', 1),
('Mon plus grand délire de jeunesse : _____', 1),
('La pire chose offerte à un baby shower : _____', 1),
('Ce qui résume parfaitement les fêtes de famille : _____', 1),
('La pire excuse pour ne pas répondre à un message : _____', 1),
('Mon plus grand fail au bureau : _____', 1),
('_____ devrait être une option dans les pages jaunes', 1),
('La pire chose entendue à la radio le matin : _____', 1),
('Ce que je ferais en cas de panne d''électricité une semaine : _____', 1),
('La pire chose dite par un chauffeur de taxi : _____', 1),
('Mon plus grand fail de drague : _____', 1),
('La pire chose à porter à un mariage : _____', 1),
('Ce qui devrait être enseigné dans les cours d''éducation civique : _____', 1),
('La pire chose découverte sur le téléphone de son meilleur ami : _____', 1),
('Mon plus grand kiff de confinement : _____', 1),
('_____, voilà mon style de vie idéal', 1),
('La pire phrase entendue en salle d''attente chez le dentiste : _____', 1),
('Ce que je ferais si je devais survivre seul sur une île : _____', 1),
('La pire chose à dire en garde à vue pour se défendre : _____', 1),
('Mon plus grand fail de cuisine partagé en famille : _____', 1),
('La pire chose offerte à Noël par un collègue : _____', 1),
('Ce qui devrait être banni des fêtes de fin d''année : _____', 1),
('La pire excuse pour ne pas faire le ménage : _____', 1),
('Mon plus grand secret de couple : _____', 1),
('_____ devrait être le nouveau sport national', 1),
('La pire chose entendue chez le dentiste : _____', 1),
('Ce que je ferais si je gagnais un voyage gratuit n''importe où : _____', 1),
('La pire chose à dire à son ex pour le/la récupérer : _____', 1),
('Mon plus grand fail en voiture : _____', 1),
('La pire chose à porter à un entretien d''embauche : _____', 1),
('Ce qui devrait être interdit pendant les repas de famille : _____', 1),
('La pire phrase à dire en sortant des toilettes publiques : _____', 1),
('Mon plus grand fail en avion : _____', 1),
('_____, ça devrait être interdit dans les open spaces', 1),
('La pire chose découverte chez ses beaux-parents : _____', 1),
('Ce que je ferais si je devais animer une émission télé : _____', 1),
('La pire chose dite pendant une garde d''enfants : _____', 1),
('Mon plus grand fail en sport collectif : _____', 1),
('La pire chose à offrir à un collègue qui part à la retraite : _____', 1);

insert into cards_answers (text) values
('La collection porno de Papi'),
('Épouser sa sœur'),
('Se finir dans un chausson aux pommes'),
('La sextape de Kim Kardashian'),
('Le traditionnel bukkake du dimanche matin'),
('L''haleine du prof de maths'),
('Surprendre papi et mamie en levrette'),
('Les mecs qui jouent à Limite Limite'),
('Un obèse qui n''arrive pas à voir sa bite'),
('Effacer l''historique'),
('Simuler un orgasme'),
('Être un FDP'),
('Attacher une brique à sa bite pour la faire grandir'),
('Une soirée Tupperware qui dégénère'),
('Le silence gênant après un pet en réunion'),
('Faire croire qu''on a un cancer pour annuler un rendez-vous'),
('Un divorce annoncé par SMS'),
('Coucher avec le meilleur ami de son frère'),
('Vomir dans le sac de quelqu''un d''autre'),
('Une crise d''hémorroïdes pendant un mariage'),
('Le caca du chat dans la litière du voisin'),
('Faire pipi dans la piscine municipale'),
('La théorie du complot de Tata Monique'),
('Un strip-tease devant la famille'),
('Se faire larguer par message vocal'),
('La cellulite de Mamie en maillot'),
('Tromper sa copine avec son ex'),
('Un divorce après 3 jours de mariage'),
('Manger les croquettes du chien par défi'),
('Une fausse couche annoncée à Thanksgiving'),
('Le slip taché de Papi qui sèche au balcon'),
('Se masturber en pensant à sa belle-mère'),
('Le speed-dating qui finit en bagarre'),
('Un coup d''un soir avec son prof de sport'),
('La gueule de bois du siècle'),
('Faire un strip-poker avec ses cousins'),
('Vomir sur les genoux du voisin dans l''avion'),
('Un selfie nu envoyé au mauvais groupe WhatsApp'),
('La virginité perdue dans une Twingo'),
('Tromper sa femme avec sa secrétaire'),
('Le calvaire d''une colo avec des poux'),
('Un test de grossesse positif aux toilettes du travail'),
('La pisse dans la piscine du voisin'),
('Se déguiser en Hitler pour Halloween'),
('Un mariage annulé à cause d''un ex jaloux'),
('Le strip-tease de Papi à Noël'),
('Coucher avec son banquier pour un prêt'),
('Un pet sonore pendant une minute de silence'),
('La cire d''oreille de Tonton dans le pot de Nutella'),
('Faire l''amour devant les enfants endormis'),
('Le préservatif retrouvé dans la machine à laver'),
('Une dépression saisonnière qui dure 10 ans'),
('Tromper son partenaire avec son thérapeute'),
('Se faire pipi dessus pendant un fou rire en classe'),
('La sextape volée de ses parents'),
('Un divorce célébré au champagne'),
('Coucher avec son patron pour une promotion'),
('Le string de Mamie retrouvé sous le canapé'),
('Une bagarre générale à un mariage'),
('Faire caca dans la douche par accident'),
('Un orgasme simulé pendant 10 minutes'),
('La crise de panique pendant un entretien d''embauche'),
('Tromper son ex avec son meilleur ami'),
('Le suppositoire oublié sur la table de la cuisine'),
('Un strip-tease raté devant les beaux-parents'),
('La gerbe pendant un karaoké'),
('Coucher avec son coach de fitness'),
('Une overdose de Nutella en pleine nuit'),
('Le string trouvé dans la voiture de son père'),
('Un mariage gay annulé par un curé homophobe'),
('Faire l''amour bruyamment chez ses parents'),
('La diarrhée explosive en plein rendez-vous Tinder'),
('Un sextoy oublié sur la table basse devant Mamie'),
('Tromper son colocataire avec son chat'),
('Le strip-poker qui finit en orgie'),
('Une crise d''angoisse pendant un examen oral'),
('Coucher avec son ex le jour de son mariage'),
('La masturbation dans les toilettes du bureau'),
('Un avortement annoncé sur Facebook'),
('Le pet silencieux mais mortel en ascenseur'),
('Une overdose de médicaments par accident'),
('Tromper sa moitié avec le facteur'),
('Le string sale retrouvé dans le micro-ondes'),
('Un coming-out raté à table'),
('La masturbation devant Netflix pendant le confinement'),
('Coucher avec deux personnes le même soir'),
('Le préservatif usagé jeté par la fenêtre'),
('Une crise existentielle un dimanche soir'),
('Tromper son partenaire pendant un EVJF'),
('La piqûre de méduse au mauvais endroit'),
('Un strip-tease devant les collègues à Noël'),
('La fellation ratée filmée par accident'),
('Un orgasme bruyant entendu par les voisins'),
('Coucher avec son professeur particulier'),
('La sodomie en option supplémentaire'),
('Un threesome qui finit mal'),
('La double pénétration accidentelle'),
('Un plan cul qui devient toxique'),
('Le sex-tape envoyé par erreur à toute la famille'),
('Une partouze de retraités'),
('La masturbation compulsive au travail');
